-- Create the role
CREATE ROLE SNOWFLAKE_ROLE;

-- Grant the role to the user
GRANT ROLE SNOWFLAKE_ROLE TO USER ADMIN;

-- Assign privileges to the role
GRANT USAGE ON DATABASE SALES_DB TO ROLE SNOWFLAKE_ROLE;
GRANT USAGE ON WAREHOUSE compute_wh TO ROLE SNOWFLAKE_ROLE;
GRANT USAGE ON SCHEMA SALES_DB.SALES_SCHEMA TO ROLE SNOWFLAKE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SALES_DB.SALES_SCHEMA TO ROLE SNOWFLAKE_ROLE;
GRANT CREATE TABLE ON SCHEMA SALES_DB.SALES_SCHEMA TO ROLE SNOWFLAKE_ROLE;
GRANT CREATE SCHEMA ON DATABASE SALES_DB TO ROLE SNOWFLAKE_ROLE;
----------------------------------------------------------------------------------------